version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_VERSION: ${NODE_VERSION:-22}
        ANGULAR_VERSION: ${ANGULAR_VERSION:-20}

    image: ghcr.io/hallboard-team/node-${NODE_VERSION}:latest
    container_name: ${CONTAINER_NAME:-frontend_angular-${ANGULAR_VERSION}_dev}

    user: "1000:1000"

    volumes:
      - ./:/workspaces/app:Z
      - ~/.cache/vscode-server-shared:/home/vscode/.vscode-server-shared:Z

    environment:
      - VSCODE_SERVER_DIR=/home/vscode/.vscode-server-shared

    ports:
      - "${PORT:-4200}:4200"

    # Container stays alive; CLI preconfigured with pnpm
    command: >
      bash -c "
        ng config -g cli.packageManager pnpm &&
        sleep infinity
      "
